name: matrix_utils
description: A Dart library that provides an easy-to-use Matrix class for performing various matrix operations and linear algebra.
version: 0.1.8
repository: https://github.com/gameticharles/matrix_utils

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  #   path:
  buffer: ^1.2.0
  intl: ^0.18.1

dev_dependencies:
  benchmark_harness: ^2.2.2
  lints: ^2.0.0
  test: ^1.21.0
